opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_unwrapping

excluded:
  - Pods
  - Vendor
  - build
  - GeneratedCode

variable_name:  
  excluded:
    - row
    - key
    - id
    - url
    - uri
    - db
    - bar
    - red
    - lhs
    - rhs
    - tag
    - rs
    - URI
    - URL

line_length: 130

type_name:
  excluded:
    - Up

nesting:
  type_level:
    warning: 2

custom_rules:
  print_usage:
    name: "Print usage"
    regex: "print\\(.*\\)"
    message: "Use log.%level% instead of print"
    severity: warning

