disabled_rules: # rule identifiers to exclude from running
  - line_length
opt_in_rules: # some rules are only opt-in
  - empty_count
  - force_unwrapping

excluded:
  - Pods
  - Vendor
  - build
  - GeneratedCode

variable_name:  
  excluded:
    - row
    - key
    - id
    - url
    - uri
    - db
    - bar
    - red
    - lhs
    - rhs
    - tag
    - rs
    - URI
    - URL

type_name:
  excluded:
    - Up

