name: MementoFM

settings:
  IPHONEOS_DEPLOYMENT_TARGET: "17.0"
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: 1
  PRODUCT_BUNDLE_IDENTIFIER: com.icecoffin.mementofm
  ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

fileGroups:
  - .swiftlint.yml
  - project.yml
  - README.md
  - Sources
  - Tests
  - Resources

targets:
  MementoFM:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - "Application/Keys.example.swift"
      - Resources
    dependencies:
      - package: Alamofire
      - package: CombineSchedulers
      - package: Realm
        product: RealmSwift
      - package: SnapKit
    info:
      path: "Supporting Files/Info.plist"
      properties:
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UILaunchStoryboardName: LaunchScreen
    preBuildScripts:
      - name: Run SwiftLint
        script: |
          if [ -d ~/.mint/bin ]; then
            echo "Adding ~/.mint/bin to PATH"
            export PATH=~/.mint/bin:$PATH
          fi

          if which swiftlint > /dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        basedOnDependencyAnalysis: false

  MementoFMTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        excludes:
          - "**/__Snapshots__"
    dependencies:
      - target: MementoFM
      - package: Realm
        product: RealmSwift
      - package: SnapshotTesting

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    exactVersion: 5.10.2
  CombineSchedulers:
    url: https://github.com/pointfreeco/combine-schedulers
    exactVersion: 1.0.3
  Realm:
    url: https://github.com/realm/realm-swift
    exactVersion: 20.0.1
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    exactVersion: 5.7.1
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing
    exactVersion: 1.17.6
